schema_version: 1

context:
  name: azure-mgmt-sql
  version: 0.24.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.zip
  sha256: da391ed00d82cd8e20ca50affdc43b99fd9a7919b54a3a0d53c73cb41eea09d3

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.0
    - pip
  run:
    - python >3.0
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common >=1.1,<2.0

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.sql
      pip_check: false

      python_version: ${{ python_min }}.*
about:
  license: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure SQL Management Client Library for Python
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - tim-werner
