schema_version: 1

context:
  name: azure-mgmt-sql
  version: 3.0.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.zip
  sha256: 129042cc011225e27aee6ef2697d585fa5722e5d1aeb0038af6ad2451a285457

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2
    - azure-mgmt-core >=1.2.0,<2.0.0
    - msrest >=0.6.21

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.sql
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure SQL Management Client Library for Python
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - tim-werner
    - janjagusch
