schema_version: 1

context:
  name: azure-mgmt-sql
  version: 4.0.0b21

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 4ad3a68025363b34792ac0d9b7ec605d0bff8ff198a664ce09c9bb2afb62d831

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2
    - isodate >=0.6.1
    - typing-extensions >=4.6.0

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.sql
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure SQL Management Client Library for Python
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - tim-werner
    - janjagusch
